name: Code Coverage

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer run-script test:coverage

      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          format: clover
          files: build/logs/clover.xml
